#!/bin/sh
#
# chkconfig: 2345 26 74
# description: 
# processname: pylon

# Source function library.
. /etc/init.d/functions

RETVAL=0
DIR=~pgillan/pylon

start() {
	echo -n $"Starting up pylon server: "
    rm -f $DIR/pylon.log
    $DIR/pylon -d -P $DIR/pylon.pid -L $DIR/pylon.log -F /tmp/pylon_dump
	RETVAL=$?
	#sleep 5;
    #$DIR/pylon_loader.pl
	echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down pylon server: "
	kill `cat $DIR/pylon.pid`
    rm -f $DIR/pylon.pid
	RETVAL=$?
	echo
	return $RETVAL
}

restart() {
	stop
	start
}

status() {
    $DIR/pylonstatus.pl
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  status)
    status
    ;;
  *)
	echo $"Usage: pylon {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL
