#!/bin/sh
#
# chkconfig: 2345 26 74
# description: 
# processname: pylon

# Source function library.
. /etc/init.d/functions

RETVAL=0
PYLON_HOME=/usr/local/pylon
TMPDIR=/tmp

start() {
	echo -n $"Starting up pylon server: "
    #rm -f $TMPDIR/pylon.log
    $PYLON_HOME/pylon -d -P $TMPDIR/pylon.pid -L $TMPDIR/pylon.log -F $TMPDIR/pylon_dump
	RETVAL=$?
    echo
	return $RETVAL
}

stop() {
	echo -n $"Shutting down pylon server: "
	kill `cat $TMPDIR/pylon.pid`
    rm -f $TMPDIR/pylon.pid
	RETVAL=$?
    echo
	return $RETVAL
}

restart() {
	stop
	start
}

status() {
    $PYLON_HOME/pylonstatus.pl
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  status)
    status
    ;;
  *)
	echo $"Usage: pylon {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL
