.\" Manpage for pylonstatus.pl
.TH man 8 "01 Apr 2016" "0.0.1-1" "pylonstatus.pl man page"
.SH NAME
pylonstatus.pl - Display stats from the pylon server.
.SH SYNOPSIS
.SH DESCRIPTION
.SH OPTIONS
.TP
No options.
.SH SEE ALSO
.TP
\fIpylon\fR(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Patrick Gillan (pgillan@minorimpact.com)
